# Generated by Django 6.0.1 on 2026-03-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtivoEletrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, verbose_name='ID do Produto')),
                ('tipo', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1)),
                ('temp_ar_k', models.FloatField(verbose_name='Temp. Ar (K)')),
                ('temp_processo_k', models.FloatField(verbose_name='Temp. Processo (K)')),
                ('rotacao_rpm', models.FloatField(verbose_name='Rotação (RPM)')),
                ('torque_nm', models.FloatField(verbose_name='Torque (Nm)')),
                ('desgaste_ferramenta_min', models.IntegerField(verbose_name='Desgaste (min)')),
                ('falha_real', models.BooleanField(default=False, verbose_name='Falha Real (Dataset)')),
                ('tipo_falha_real', models.CharField(blank=True, max_length=50, null=True)),
                ('status_matematico', models.CharField(blank=True, max_length=100, null=True)),
                ('predicao_ia_risco', models.FloatField(blank=True, null=True, verbose_name='Risco IA (%)')),
                ('data_leitura', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Monitoramento de Ativo',
                'verbose_name_plural': 'Monitoramento de Ativos',
            },
        ),
    ]
